name: Bot de Tuits (Buffer)

on:
  schedule:
    - cron: '01 23 * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  publicar_a_buffer:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar el codi
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instal·lar dependències
        run: pip install requests

      - name: Executar el bot
        env:
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          BUFFER_PROFILE_ID: ${{ secrets.BUFFER_PROFILE_ID }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TIPUS="${{ github.event.inputs.tipus }}"
            
            # Si el tipus arriba buit per algun motiu, li assignem 'tots' per evitar l'error
            if [ -z "$TIPUS" ]; then
              TIPUS="tots"
            fi
            
            PARAULA="${{ github.event.inputs.paraula }}"
            echo "Llançant el bot en mode manual. Tipus: $TIPUS | Paraula forçada: $PARAULA"
            
            CMD="python bot/main.py --tipus $TIPUS"
            if [ -n "$PARAULA" ]; then
              CMD="$CMD --paraula \"$PARAULA\""
            fi
            eval $CMD
          else
            echo "Llançant el bot en mode automàtic"
            python bot/main.py
          fi
 
      - name: Desar l'històric (Git Commit & Push)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Afegim tots els json de la carpeta bot que hagin canviat
          git add bot/publicades_*.json
          
          # Fem el commit només si l'script Python ha modificat algun JSON
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Actualitza el registre de tuits publicats als JSON"
          
          git push