name: Deploy Gulp site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detectar canvis en CSS o JS
        id: canvis
        uses: tj-actions/changed-files@v42
        with:
          files: |
            css/*.css
            js/*.js

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Gulp
        run: npx gulp

      - name: Rebentar Memòria Cau (Actualitzar versions HTML)
        if: steps.canvis.outputs.any_changed == 'true'
        run: |
          NOVA_VERSIO=${GITHUB_SHA::7}
          echo "S'han detectat canvis al codi! Aplicant la versió $NOVA_VERSIO als HTML..."
          
          find . -type f -name "*.html" -exec sed -i -E "s/(\.js\?v=)[^\"]*/\1$NOVA_VERSIO/g" {} +
          find . -type f -name "*.html" -exec sed -i -E "s/(\.css\?v=)[^\"]*/\1$NOVA_VERSIO/g" {} +

      - name: Guardar els HTML actualitzats al repositori
        if: steps.canvis.outputs.any_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add '*.html' '**/*.html'
          git commit -m "Cache busting: versions actualitzades als HTML" || echo "No hi ha canvis"
          git push

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4