name: Generador de diccionaris (i de fènixs i heptasíl·labs)

on:
  push:
    paths:
      - 'diccionaris/separat/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Preprocés (generar col_10provisional a partir de les parts de col_10)
        working-directory: diccionaris
        run: python "pre_proces.py"

      - name: Crear diccionari
        working-directory: diccionaris
        run: python "creador_rima + dicc (a partir de col_10).py"

# --- comit diccionari ---
      - name: Comit diccionari i columnes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Generació automàtica del diccionari i les columnes" || echo "No s'han detectat canvis nous per guardar"
          git push

      - name: Postprocés (regenerar les parts de col_10 i eliminar col_10provisional)
        working-directory: diccionaris
        run: python "post_proces.py"

# --- comit diccionari ---
      - name: Comit columna 10 separada
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Generació automàtica de la columna_10 separada" || echo "No s'han detectat canvis nous per guardar"
          git push


      - name: Crear llista de fenixs
        working-directory: llistes
        run: python generar_fenixs.py

# --- comit diccionari ---
      - name: Comit llista de fènixs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Generació automàtica de la llista de fènixs" || echo "No s'han detectat canvis nous per guardar"
          git push


      - name: Crear llista de mots_de7
        working-directory: llistes
        run: python generar_mots_de7.py

# --- comit diccionari ---
      - name: Comit llista de mots de 7
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Generació automàtica de la llista de mots de 7" || echo "No s'han detectat canvis nous per guardar"
          git push


      - name: Incrementa versió de transcripcions (+1)
        run: |
          jq '.transcripcions += 1' diccionaris/versions.json > "$tmp" && mv "$tmp" diccionaris/versions.json
          echo "Nova versió generada:"
          cat diccionaris/versions.json

      - name: Commit i Push de la versió
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add diccionaris/versions.json
          git commit -m "+1 a la versió de transcripcions [automàtic]" || echo "No hi ha canvis"
          git push