name: Generador de diccionaris (i de fènixs i heptasíl·labs)

on:
  push:
    paths:
      - 'diccionaris/separat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Preprocés (generar col_10provisional a partir de les parts de col_10)
        working-directory: diccionaris
        run: python "pre_proces.py"


      - name: Crear diccionari
        working-directory: diccionaris
        run: python "creador_rima + dicc (a partir de col_10).py"


      - name: Postprocés (regenerar les parts de col_10 i eliminar col_10provisional)
        working-directory: diccionaris
        run: python "post_proces.py"


      - name: Crear llista de fenixs
        working-directory: llistes
        run: python generar_fenixs.py

      - name: Crear llista de mots_de7
        working-directory: llistes
        run: python generar_mots_de7.py
