name: Fenixs workflow

on:
  push:
    paths:
      - 'diccionaris/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Crear diccionari
        working-directory: rimador.github.io/diccionaris
        run: python creador_rima + dicc.py

      - name: Separar diccionari
        working-directory: rimador.github.io/diccionaris
        run: python separar_arxiu.py

      - name: Crear llista de fenixs
        working-directory: rimador.github.io
        run: python generar_fenixs.py

      - name: Crear llista de mots_de7
        working-directory: rimador.github.io
        run: python generar_mots_de7.py
